server:
  port: 9003

spring:
  application:
    name: SAVED-JOBS-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://18.191.173.190:8761/eureka/
    instance:
      hostname: 18.191.173.190