server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: LOCATIONS-SERVICE
          uri: lb://LOCATIONS-SERVICE
          predicates:
            - Path=/locations/**
        - id: JOBS-SERVICE
          uri: lb://JOBS-SERVICE
          predicates:
            - Path=/jobs/**
        - id: APPLIED-JOBS-SERVICE
          uri: lb://APPLIED-JOBS-SERVICE
          predicates:
            - Path=/appliedJobs/**
        - id: SAVED-JOBS-SERVICE
          uri: lb://SAVED-JOBS-SERVICE
          predicates:
            - Path=/savedJobs/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://18.191.173.190:8761/eureka/
    instance:
      preferIpAddress: true
      hostname: 18.191.173.190