name: CICD
on:
  push:
    branches:
      - deployback
  #   paths:
  #     - "backend/**"
  # pull_request:
  #   types: [opened, synchronize, reopened]

jobs:

# ---------------------------------------------|___BUILD___|------------------------------------------------------------

  backend-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [service-registry, cloud-gateway, jobs, locations, applied-jobs, saved-jobs]

    defaults:
      run:
        working-directory: backend/${{ matrix.service }}
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: for maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: mnv clean
        run: mvn clean install -DskipTests=true
      

        
      - name: building image for ${{ matrix.service }}
        run: docker build . -t ${{ secrets.PACKAGE_URL }}/${{ secrets.REGISTRY_USERNAME }}/bc55_${{ matrix.service }}:latest

      - name: login to github packages
        run: docker login ${{ secrets.PACKAGE_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_TOKEN }}

      - name: pushing image
        run: docker push ${{ secrets.PACKAGE_URL }}/${{ secrets.REGISTRY_USERNAME }}/bc55_${{ matrix.service }}:latest


#-------------------------------------------------|__DEPLOYMENT__|----------------------------------------------------------- 

  
  backend-deploy:
    name: deploy to EC2
    runs-on: ubuntu-latest
    needs: 
    - backend-build

    steps:
      - name: checking into repo
        uses: actions/checkout@v2

      - name: Add SSH key    
        run: |
            mkdir -p /home/runner/.ssh
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
            echo -e "${{ secrets.HIMANK_PVT_KEY}}" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions          
            
      - name: run script for deploy
        run: |
          ssh ubuntu@18.191.173.190 -i ~/.ssh/github_actions "docker login ${{ secrets.PACKAGE_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_TOKEN }}
          docker-compose down
          docker rmi ${{ secrets.PACKAGE_URL }}/${{ secrets.REGISTRY_USERNAME }}/bc55_service-registry:latest ${{ secrets.PACKAGE_URL }}/${{ secrets.REGISTRY_USERNAME }}/bc55_cloud-gateway:latest ${{ secrets.PACKAGE_URL }}/${{ secrets.REGISTRY_USERNAME }}/bc55_jobs:latest ${{ secrets.PACKAGE_URL }}/${{ secrets.REGISTRY_USERNAME }}/bc55_locations:latest ${{ secrets.PACKAGE_URL }}/${{ secrets.REGISTRY_USERNAME }}/bc55_applied-jobs:latest ${{ secrets.PACKAGE_URL }}/${{ secrets.REGISTRY_USERNAME }}/bc55_saved-jobs:latest
          docker-compose up -d" 

